import type { Metadata } from 'next';
import { ArrowUpRight } from 'lucide-react';
import Reveal from '@/components/Reveal';
import LandingVideo from '@/components/marketing/LandingVideo';
import InstallCommand from '@/components/marketing/InstallCommand';
import { ProductHeader, ProductFooter } from '@/components/marketing/MarketingShell';
import s from '@/components/marketing/marketing.module.css';
const repo = 'https://github.com/PabloG55/ghostfleet';
export const metadata: Metadata = { metadataBase: new URL('https://ghostfleet.pablogarces.dev'), title: 'Ghostfleet | One terminal. A whole fleet.', description: 'Run Claude, Codex, and OpenCode side by side in isolated worktrees. Persistent tmux sessions and mobile access for your coding agents.', alternates: { canonical: 'https://ghostfleet.pablogarces.dev' }, icons: { icon: '/marketing/ghostfleet-favicon.png', apple: '/marketing/ghostfleet-icon.webp' }, openGraph: { title: 'Ghostfleet — One terminal. A whole fleet.', url: 'https://ghostfleet.pablogarces.dev', images: ['/projects/ghostfleet/stack-poster.webp'] } };
export default function GhostfleetHome() { return <div id="top" className={`${s.page} ${s.ghostfleet}`}>
<ProductHeader name="ghostfleet" icon="/marketing/ghostfleet-icon.webp" links={[{ label: 'Workflow', href: '#workflow' }, { label: 'Mobile', href: '#mobile' }]} action={{ label: 'GitHub', href: repo }} />
<main className={s.container}>
<div className={s.ghostHero}><div className={s.hero}><span className={s.eyebrow}>Open source · macOS / Linux / WSL2</span><h1>One terminal.<br /><span className={s.accent}>A whole fleet.</span></h1><p>Give each coding agent its own worktree. Run Claude, Codex, and OpenCode side by side, and keep their sessions alive after you close the window.</p><InstallCommand /><div className={s.actions}><a className={s.textLink} href={`${repo}#readme`}>Read the setup guide <ArrowUpRight size={15} /></a><a className={s.textLink} href={repo}>Explore the source <ArrowUpRight size={15} /></a></div></div><div className={s.terminalBar}><i /><i /><i /><span>ghostfleet · Claude / OpenCode / Codex</span></div><LandingVideo className={s.terminalVideo} src="/projects/ghostfleet/stack-demo.mp4" poster="/projects/ghostfleet/stack-poster.webp" label="Three coding agents running side by side in Ghostfleet" /><p className={s.note}>Actual Ghostfleet session · three interactive agents, visible at once.</p></div>
<section id="workflow" className={s.section}><Reveal><span className={s.eyebrow}>Parallel work without losing the thread</span><h2>Different tasks.<br />Room for each one.</h2><div className={s.features}><article><h3>Worktrees, not collisions.</h3><p>Each agent gets an isolated Git worktree. Keep tasks on separate branches instead of asking multiple agents to edit the same checkout.</p></article><article><h3>Sessions that stick around.</h3><p>Per-project tmux sessions keep your terminals alive. Close a window, come back later, and reconnect to the work already in progress.</p></article><article><h3>See the whole fleet.</h3><p>Stack interactive agents in one view. Watch their output, answer a question, or switch focus without hunting through terminal windows.</p></article></div></Reveal></section>
<section className={s.section}><Reveal><div className={s.split}><div><span className={s.eyebrow}>From a task to a working session</span><h2>Give the work<br />its own workspace.</h2><p>Create a worktree, launch an agent, and return to the project when you need to. Reuse existing worktrees and keep your sessions tied to the repository.</p><p>Resource and budget controls help you manage a growing fleet.</p></div><LandingVideo src="/projects/ghostfleet/demo.mp4" poster="/projects/ghostfleet/poster.webp" label="Ghostfleet worktree and agent session walkthrough" /></div></Reveal></section>
<section id="mobile" className={s.section}><Reveal><div className={s.split}><div className={s.mobileVideo}><LandingVideo src="/marketing/ghostfleet-mobile.mp4" poster="/marketing/ghostfleet-mobile.webp" label="Ghostfleet mobile chat and terminal walkthrough" /></div><div><span className={s.eyebrow}>Your fleet, away from your desk</span><h2>An agent is waiting.<br />You don’t have to be.</h2><p>The mobile web app brings session chat and terminal access to your phone. Check progress, answer an agent, and unblock a task without returning to your computer.</p><a className={s.textLink} href={`${repo}#readme`}>Set up mobile access <ArrowUpRight size={14} /></a></div></div></Reveal></section>
<section className={s.section}><Reveal><h2>Before you launch.</h2><div className={s.faq}><details><summary>Which agents can I use?</summary><p>Claude, Codex, and OpenCode are supported. Install and authenticate the agents you want to run; Ghostfleet organizes their sessions.</p></details><details><summary>What do I need installed?</summary><p>Node.js, Git, tmux, jq, and curl. The repository setup guide covers prerequisites and configuration.</p></details><details><summary>Does it work on Windows?</summary><p>Use WSL2. Ghostfleet supports macOS, Linux, and WSL2; native Windows is not supported.</p></details><details><summary>Can I try the interface first?</summary><p>Use <code>ghostfleet demo</code> after installation to explore its demo mode. The source and setup instructions are available on GitHub.</p></details></div></Reveal></section>
<section className={`${s.section} ${s.closing}`}><Reveal><h2>Give your agents a home.</h2><InstallCommand /><div className={s.actions}><a className={s.textLink} href={`${repo}#readme`}>Installation & documentation <ArrowUpRight size={15} /></a></div></Reveal></section>
</main><ProductFooter name="ghostfleet" app="ghostfleet"><a href={repo}>Source</a><a href={`${repo}#readme`}>Documentation</a><a href={`${repo}/issues`}>Issues</a></ProductFooter></div>; }
